trigger:
- master

resources:
  repositories:
  - repository: self  
  - repository: MathTrickCore 
    name: MathTrickCore
    type: git

variables:
  dockerRegistryServiceConnection: 'ACR Connection'
  imageRepository: 'mt3gateway-step1'
  containerRegistry: '<your-acr>.azurecr.io'
  dockerfilePath: '$(Agent.BuildDirectory)/Gateway/MT3Chained-Step1/Dockerfile'
  selfRepoPath: 'Gateway/MT3Chained-Step1'
  tag: 'v$(Build.BuildId)'
  vaultName: '<your-keyvault>'
  secretTagName: 'mt3gateway-step1-tag'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage

  jobs:
  - job: Build    
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: MathTrickCore 
      path: MathTrickCore     
    - checkout: self
      path: $(selfRepoPath)
    - task: Docker@2      
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        buildContext: $(Agent.BuildDirectory)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag),latest
        
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure Connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az keyvault secret set --vault-name "$(vaultName)" --name "$(secretTagName)" --value "$(tag)"
